#!/usr/bin/env ruby
#
# This script handles receiving emails in order to reprocess them, e.g. for group emails.
# Have a look at these resources:
#
#   * http://railscasts.com/episodes/313-receiving-email-with-mailman.
#   * https://github.com/titanous/mailman
#   * http://rubydoc.info/github/titanous/mailman/master/file/USER_GUIDE.md
#

require "rubygems"
require "bundler/setup"
require "mailman"
require 'yaml'

config_file = File.expand_path('../../config/group-mail-worker.yml', __FILE__)
if not File.exists? config_file
  raise "The config/group-mail-worker.yml (#{config_file}) was not found! Group mail worker could not be started!"
else

  config = YAML.load(File.read(config_file))
  
  Mailman.config.logger = Logger.new("log/mailman.log")
  Mailman.config.maildir = config["maildir"]
  
  p "mailman: configuration set. starting mailman application ..."
  Mailman::Application.run do
  
    p "mailman run ..."
    p "monitoring #{Mailman.config.maildir}/new."
    to '%token%@wingolfsplattform.org' do
      
      begin
        Mailman.logger.info "Processing incoming email:\n#{message}"
        post = Post.create_from_message(message)
        Mailman.logger.info "Processing completed. Created post #{post.id}."
      rescue Exception => e
        Mailman.logger.error "Exception occured while processing received email:\n#{message}"
        Mailman.logger.error [e, *e.backtrace].join("\n")
      end
  
    end
  end
end


# This file is still in development.
# Try this using 
#
#   cat mailman_test.eml | script/mailman_server
