name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6 for general purpose
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Build docker containers for YourPlatform
        run: docker-compose build
      - name: Prepare specs to run in tests container
        run: docker-compose run tests /bin/bash -c "bundle install && bundle exec rake prepare_tests"
      - name: Run model specs in tests container
        run: docker-compose run tests /bin/bash -c "bundle exec rspec spec/models"